In [9]:
import sys
import numpy as np
import cv2
import tensorflow as tf

print(sys.version)
print(cv2.__version__) 
print(tf.__version__)
print("3.6.3 |Anaconda custom (64-bit)| (default, Oct 15 2017, 03:27:45) [MSC v.1900 64 bit (AMD64)] 3.3.0 1.4.0")

3.6.8 (default, Oct  7 2019, 12:59:55) 
[GCC 8.3.0]
4.0.0
1.4.0
3.6.3 |Anaconda custom (64-bit)| (default, Oct 15 2017, 03:27:45) [MSC v.1900 64 bit (AMD64)] 3.3.0 1.4.0


In [10]:
#useful stuff
print(np.ones((3,3))+np.arange(3))

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [13]:
mask = np.array([False,True,False])
l = np.ones((1,3))

IndexError: boolean index did not match indexed array along dimension 0; dimension is 1 but corresponding boolean dimension is 3